version: 2.1

orbs:
  terraform: circleci/terraform@3.2.1

jobs:
  validate:
    docker: 
      - image: cimg/base:stable
    steps:
      - checkout
      - terraform/init
      - run:
          name: Terraform Validate
          command: terraform validate
  
  plan:
    docker:
      - image: cimg/base:stable 
    steps:
      - checkout
      - terraform/init
      - run:
          name: Terraform Plan
          command: terraform plan -out=plan

  apply:
    docker:
      - image: cimg/base:stable  
    steps:
      - checkout
      - terraform/init
      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve

  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: 
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Tests
          command: pytest

  destroy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - terraform/init
      - run:
          name: Terraform Destroy
          command: terraform destroy -auto-approve
          
workflows:
  deploy:
    jobs:
      - validate
      - plan:
          requires:
            - validate
      - hold:
          type: approval
          requires:
            - plan
      - apply:
          requires:
            - hold
      - test:
          requires:
            - apply
      - hold-2: 
          type: approval
          requires:
            - test
      - destroy:
          requires:
            - hold-2