version: 2.1

orbs:
  terraform: circleci/terraform@3.2.1
  aws-cli: circleci/aws-cli@4.0.0

jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: 
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Tests
          command: pytest
workflows:
  deploy_infrastructure:
    jobs:
      - aws-cli/setup:
          context: aws
      - terraform/validate:
          checkout: true
          context: terraform
      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate
            - aws-cli/setup
      - hold:
          type: approval
          requires:
            - terraform/plan      
      - terraform/apply:
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: main
          requires:
            - hold
      - test:
          requires:
            - terraform/apply
      - hold-2: 
          type: approval
          requires:
            - test
      - terraform/destroy:
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: main
          requires:
            - hold-2